### ISSUE TITLE
Can i dual-boot this?

### ISSUE THREAD

**Issue by mfat** [PrivateRouter-LLC/openwrt-x86#1]
Is it possible to dual boot this with ubuntu?

**Comment by torguardops** [comment]
I would say no as this is built to run on an extra computer that works as a router and has other services for self hosting such as Docker. If you want to run it on the same computer you use all the time, you CAN use this from a USB drive but still not something I would recommend. This basically is an image you flash to a whole drive then use partition software to take up the rest of the drive.

I will say you COULD flash this first then install something on the rest of the drive but again this is not meant to be used as a dual setup.
