### ISSUE TITLE
Cant run balenaEtcher Appimage

### ISSUE THREAD

**Issue by cams1303** [PrivateRouter-LLC/openwrt-x86#5]
The balenaEtcher Appimage on the linux mint desktop will not run, double click, right click nothing happens.
Is there a list of CPU support as this is an Intel N100

**Comment by FixedBit** [comment]
Hey there, sometimes you have to do "chmod +x nameof.app" on the etcher binary to get it to work, then you can do "./nameof.app" to execute it. Hope that helps!
